import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../../theme-provider";
import { cn } from "@/lib/utils";
import MaxWidthWrapper from "@/components/global/max-width-wrapper";
import Navbar from "@/components/global/navbar";
import Footer from "@/components/global/footer";
import { DotPattern } from "@/components/magicui/dot-pattern";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <DotPattern
            width={20}
            height={20}
            cx={1}
            cy={1}
            cr={1}
            className={cn(
              "[mask-image:linear-gradient(to_bottom_right,white,transparent,transparent)] "
            )}
          /> */}
          {/* <MaxWidthWrapper> */}
          <Navbar />
          {children}
          <Footer />
          {/* </MaxWidthWrapper> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
